# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: src/grpc_output/sum_amount.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n src/grpc_output/sum_amount.proto\x12\x14transactions_service\"p\n\x10SumAmountRequest\x12\x11\n\tuser_uuid\x18\x01 \x01(\t\x12\x1b\n\x13timestamp_start_utc\x18\x02 \x01(\t\x12\x19\n\x11timestamp_end_utc\x18\x03 \x01(\t\x12\x11\n\tdirection\x18\x04 \x01(\t\"F\n\x11SumAmountResponse\x12\x12\n\nsum_amount\x18\x01 \x01(\t\x12\x1d\n\x15response_time_seconds\x18\x02 \x01(\x01\x32l\n\x0cTransactions\x12\\\n\tSumAmount\x12&.transactions_service.SumAmountRequest\x1a\'.transactions_service.SumAmountResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'src.grpc_output.sum_amount_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SUMAMOUNTREQUEST']._serialized_start=58
  _globals['_SUMAMOUNTREQUEST']._serialized_end=170
  _globals['_SUMAMOUNTRESPONSE']._serialized_start=172
  _globals['_SUMAMOUNTRESPONSE']._serialized_end=242
  _globals['_TRANSACTIONS']._serialized_start=244
  _globals['_TRANSACTIONS']._serialized_end=352
# @@protoc_insertion_point(module_scope)
